// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njxwubxskmgyxhgxkctf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qeHd1Ynhza21neXhoZ3hrY3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTMzNDMsImV4cCI6MjA3NDIyOTM0M30.DLxDpI9OOVySugDl9Y6U9MxeZj4VZvY2RNAOFPSEWzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});